### ISSUE TITLE
Internal server error when field is outside study area

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#103]
It is not clear when the error appears; probably when the field is outside the study area and the user attempts to change its co-ordinates.

**Comment by kickapoo** [comment]
This issue is more `pthlema.spatial` issue than `aira`. More or less, there is a need for a method in `pthelma.spatial` that given a point check if point exist in a given raster. 
Check this line in `aira` : https://github.com/openmeteo/aira/blob/master/aira/irma/main.py#L137. This is our best way to check this, we can always make adjustments according server errors from users but the bottom line is we need a simple True, False method from `pthelma.spatial`.

**Comment by aptiko** [comment]
Could you please reproduce the error and paste the traceback here?

**Comment by kickapoo** [comment]
Unfortunately i can't reproduce the error but in `pthlema.raster2point` in the case of  point outside the `mask` file reproduce the following error
``` 
IRMA/coeffs_data/fc.tif, band 1: Access window out of range in RasterIO().  Requested
(-2271,1896) of size 1x1 on raster of 461x420.
```

**Comment by aptiko** [comment]
OK. I managed to reproduce the error. It's when the co-ordinates are totally out of range. Here's steps to reproduce:

1. Create a new field with latitude 500 and longitude 500. This will work and you will be returned to the "my fields" page.
2. Try to go to go to the edit field page for that field. You get a ValueError.

**Comment by kickapoo** [comment]
So probably, 
``` 
/pthelma/spatial.py in extract_point_from_raster
   (190):  px, py = int(px + 0.5), int(py + 0.5) 
```
must `raise RuntimeError'.
