### ISSUE TITLE
Show data when clicking on the map

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#66]
I configured some stuff on mapserver. Try this:

http://arta.irrigation-management.eu/cgi-bin/mapserver?map=/var/cache/pthelma/mapserver-historical.map&info_format=text/html&LAYERS=Daily_temperature_2015-04-06&SERVICE=WMS&VERSION=1.1.1&SRS=EPSG:4326&BBOX=20.7543,38.9926,21.1385,39.2669&WIDTH=256&HEIGHT=256&REQUEST=GetFeatureInfo&QUERY_LAYERS=Daily_temperature_2015-04-06,Daily_wind_speed_2015-04-06&X=200&Y=130

Some things may need explaining. Ask questions.

**Comment by kickapoo** [comment]
This link provides a `text/html`  and displays `Temp` and `Wind` values. My first thought is to use `x,y` from mouseposition coordinates and provide to the user some kind of interaction, like a `pop up` with the values. So, url's last `X`,`Y` values  is something that i could use? I can assume that `200` and `130` can't be coordinates.
Also, `date` is already input variable in map creation init call so implementation of `Daily_temperature_date` etc won't be a problem.

**Comment by nmalamos** [comment]
The idea is right. I think that in the Openlayers example page (http://openlayers.org/en/v3.4.0/examples/) there is all the necessary info.
I tried it with all layers in "QUERY_LAYERS" and I got this a a result:
<blockquote>Temperature = 12.360496 Â°C <br>
Evaporation = 1.0149659 mm<br>
Humidity = 82.114784%<br>
Rain = 15.42164 mm<br>
Solar radiation = 37.956032 W/mÂ²<br>
Wind speed = 1.8297749 m/s</blockquote>

We need a header showing the date and proper rounding of the results.
The only strange is the <b>Â</b>

http://arta.irrigation-management.eu/cgi-bin/mapserver?map=/var/cache/pthelma/mapserver-historical.map&info_format=text/html&LAYERS=Daily_temperature_2015-04-06&SERVICE=WMS&VERSION=1.1.1&SRS=EPSG:4326&BBOX=20.7543,38.9926,21.1385,39.2669&WIDTH=256&HEIGHT=256&REQUEST=GetFeatureInfo&QUERY_LAYERS=Daily_solar_radiation_2015-04-06,Daily_humidity_2015-04-06,Daily_rain_2015-04-06,Daily_temperature_2015-04-06,Daily_wind_speed_2015-04-06,Daily_evaporation_2015-04-06&X=200&Y=130

**Comment by aptiko** [comment]
Indeed, by changing `query_layers` you can specify which values to get.

The Â is because mapserver does not specify an encoding, and your browser assumes ISO-8859-1, when in fact it is UTF-8. I think this will probably be OK in the popup, we'll see. So far I haven't found a way to round the values, but I will keep looking.

Assume a `width` × `height` grid that contains the specified `bbox`. Then `x` and `y` are the pixel co-ordinates in that grid, so `x=200` and `y=130` will give you the pixel that is in these co-ordinates. I believe that `0 <= x < width` and `0 <= y < height`.

Maybe a good solution would be to create a small `bbox` (i.e. a few meters around the point you are interested in), and specify `width=1`, `height=1`, `x=0` and `y=0`, but I don't know if it will work, you need to experiment.

**Comment by kickapoo** [comment]
Just a small `doc` review because i bit lost. 
First of all, `aira` uses `Openlayers 2` , so the first question might be if we need to upgrade to `Openlayers 3`. 

`Openlayers 2/api` has the `OpenLayers.Control.WMSGetFeatureInfo` which adds a control to the `OpenLayers.Layer.WMS` . In order to work, `eventListeners` functions must be written in order to handle  the request data.  Also, based on the experience in `QGIS` maybe `OpenLayers.Control.WMTSGetFeatureInfo` is more suitable. 

`Openlayer 3/api` has a different approach which is still fuzzy for me. The official example can be found here, http://openlayers.org/en/v3.4.0/examples/getfeatureinfo-tile.html, and `javascript` code here, `http://openlayers.org/en/v3.4.0/examples/getfeatureinfo-tile.js`

Based on the above, i think @aptiko  solution with `bbox` is  more straightforward to our needs, 
for example (and please tell me opinion) i could create the following scenario:
1. Under the map, a small div to render results
2. Create a `ajax` call within our `aira.views` that:
    i) using `mouseover` coordinates and `date` as arguments
   ii) create a `bbox` variable
   ii) web scrap (or get the data with some other way) the url from WMS
  iii) update div

**Comment by aptiko** [comment]
No, OpenLayers 2 is fine. It also has [examples][1], though maybe not exactly what we are trying to do. So solve it in whatever way is easiest. Don't try to parse the contents of the returned HTML; just display it as it is. We will improve it after we manage to get it to work. If you want something different in the resulting HTML, tell me.

  [1]: http://dev.openlayers.org/releases/OpenLayers-2.13.1/examples/

**Comment by nmalamos** [comment]
Considering the recall of coordinates form the map, the corresponding OpenLayers 2 example (http://dev.openlayers.org/releases/OpenLayers-2.13.1/examples/getfeatureinfo-popup.html) provides a straightforward solution at line 53:
<blockquote>info = new OpenLayers.Control.WMSGetFeatureInfo({ <br>
            url: 'http://demo.opengeo.org/geoserver/wms', <br>
            title: 'Identify features by clicking',<br>
            queryVisible: true,<br>
            eventListeners: {<br>
                getfeatureinfo: function(event) {<br>
                    map.addPopup(new OpenLayers.Popup.FramedCloud(<br>
                        "chicken", <br>
                       <b> map.getLonLatFromPixel(event.xy),<br></b>
                        null,<br>
                        event.text,<br>
                        null,<br>
                        true<br>
                    ));<br>
                }<br>
            }<br>
        });<br>
</blockquote>

This is what I have done in order to get featureinfo responses from the map at:http://geo.teimes.gr/web/apps/apps1/
<blockquote>
info = new OpenLayers.Control.WMSGetFeatureInfo({<br>
url: 'http://geo.teimes.gr:8080/TEI/wms',<br>
title: 'Identify features by clicking',<br>
<b>layers: [Arta_soils_WGS84],<br></b>
queryVisible: true,<br>
eventListeners: {<br>
getfeatureinfo: function(event) {<br>
map.addPopup(new OpenLayers.Popup.FramedCloud(<br>
"chicken",<br>
<b>map.getLonLatFromPixel(event.xy),<br></b>
null,<br>
event.text,<br>
null,<br>
true<br>
));<br>
}<br>
}<br>
});<br>
</blockquote>

**Comment by kickapoo** [comment]
@nmalamos , i was trying the code you referring without results. I will give it another try

**Comment by kickapoo** [comment]
@aptiko,  based on the code that @nmalamos  also referring, below is the url that is reproduced

http://arta.irrigation-management.eu/cgi-bin/mapserver?map=/var/cache/pthelma/mapserver-historical.map&LAYERS=Daily_temperature_2015-04-06&QUERY_LAYERS=Daily_temperature_2015-04-06&STYLES=&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&BBOX=2284270.107574%2C4734237.484898%2C2386695.725462%2C4752123.749515&FEATURE_COUNT=10&HEIGHT=117&WIDTH=670&FORMAT=image%2Fpng&INFO_FORMAT=text%2Fhtml&SRS=EPSG%3A3857&X=298&Y=95

As you can see, more or less, is very close the desired url.

I have a problem with `localhost:8000` that limits me and produce the error, 
`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

In order to test the map , I am using a simple `html` page and `python -m SimpleHTTPServer 8000`. 
Any ideas how i can set my development environment to bypass the above error ?

**Comment by nmalamos** [comment]
Take a look at this: http://gis.stackexchange.com/questions/52547/i-create-getfeatureinfo-with-popup-but-it-dosnt-work-error-404
I had the same problem and I solved it with the use of <i>ProxyHost</i>.
Without the use of <i>proxy.cgi</i> (ln 188 of http://geo.teimes.gr/web/apps/apps1/) the getfeatureinfo wouldn't work at all.
I cannot recall of any other tricks, that I implemented.

**Comment by kickapoo** [comment]
I have already done this. I will give it try.

Neverless my 'ajax' calls are ready and tomorrow I will give a final try.

**Comment by kickapoo** [comment]
As i move to another solution, 
Using `OpenLayers.ProxyHost = "/cgi-bin/proxy.cgi?url=";`  produce the following url:

http://localhost:8000/cgi-bin/proxy.cgi?url=http%3A%2F%2Farta.irrigation-management.eu%2Fcgi-bin%2Fmapserver%3Fmap%3D%2Fvar%2Fcache%2Fpthelma%2Fmapserver-historical.map%26LAYERS%3DDaily_temperature_2015-04-06%26QUERY_LAYERS%3DDaily_temperature_2015-04-06%26STYLES%3D%26SERVICE%3DWMS%26VERSION%3D1.1.1%26REQUEST%3DGetFeatureInfo%26BBOX%3D2284346.544602%252C4716656.968395%252C2386619.288434%252C4769704.266018%26FEATURE_COUNT%3D10%26HEIGHT%3D347%26WIDTH%3D669%26FORMAT%3Dimage%252Fpng%26INFO_FORMAT%3Dtext%252Fhtml%26SRS%3DEPSG%253A3857%26X%3D346%26Y%3D183

which leads to `404` error.

**Comment by aptiko** [comment]
I made some changes in the configuration of mapserver.

First, you can now access mapserver at http://arta.irrigation-management.eu/mapserver-historical and http://arta.irrigation-management.eu/mapserver-forecast. Please use these addresses as the WMS base addresses instead of http://.../cgi-bin/mapserv?map=/var/cache/pthelma/mapserver-historical.map. You should not specify the `map` argument when using the new addresses.

The new addresses now also include the `Access-Control-Allow-Origin` header, so you should now be able to debug it without using the proxy.

**Comment by kickapoo** [comment]
First of all, the new url from the previous comment , also produce the same error. 

Moving on to the `ajax` based solution and i need your help with the `BBOX` parameter. 

I have created a functionality similar to `add field` where the user can click on the map and create a marker with auto-fills coordinates to the form.
In our current problem, user can click on the map, a marker appear and for debugging reasons an `alert` box appears like the following pic. The alert box shows in  `lat`,`lon`,`temp`,`date`

![screenshot 2015-04-21 18 21 22](https://cloud.githubusercontent.com/assets/5064612/7255780/2fafa9f4-e854-11e4-8d60-16a90be6a90e.png)

Map `onclick` event function calls the following `view` function: 

```python
def ajax(request, lat, lon, date="2015-04-06"):
    data = {}
    data['lat'] = lat
    data['lon'] = lon
    data['date'] = date
    print str(date), type(str(date))
    wms_url = "http://arta.irrigation-management.eu/cgi-bin/mapserver?map=/var/cache/pthelma/mapserver-historical.map&info_format=text/html&LAYERS=Daily_temperature_" + str(date) +"&SERVICE=WMS&VERSION=1.1.1&SRS=EPSG:4326&BBOX=20.7543,38.9926,21.1385,39.2669&WIDTH=256&HEIGHT=256&REQUEST=GetFeatureInfo&QUERY_LAYERS=Daily_temperature_" +str(date)+"&X=200&Y=130"
    response = urllib2.urlopen(wms_url)
    html = response.read()
    print html
    data['temp'] = html[14:18]
    response.close()
    return HttpResponse(json.dumps(data),
                        content_type="application/json")
```


So, summarising, for the `BBOX=20.7543,38.9926,21.1385,39.2669`  , with the above code i can get the corresponding value for any `date`. For example, the attached img show in the case of `date=2015-04-01`

If the above solution might consider valid, I need help understand the `BBOX` parameter. 

The main question is , that given a pair of lat,lon, may i consider it as the center of a small box? If yes, i could find some mathematical function from trigonometry that could help me to make the `BBOX`. 

Also, the 2 pairs of coords of the url's `BBOX` parameter is the upper left and bottom-right corners?

**Comment by kickapoo** [comment]
Also, from WMS Server documentation (http://mapserver.org/el/ogc/wms_server.html) 

BBOX=minx,miny,maxx,maxy: Bounding box corners (lower left, upper right) in SRS units.

Any ideas, how i could construct  `minx,miny,maxx,maxy` from a single point ?

**Comment by nmalamos** [comment]
The bouncing box, in the gis terminology,represents a rectangle that

**Comment by nmalamos** [comment]
Something is obviously wrong with the server side.
I tried adding a layer from the WMS service (which is working fine) to my geoserver, here:
http://geo.teimes.gr:8080/TEI/wms?service=WMS&version=1.1.0&request=GetMap&layers=TEI:Daily_evaporation_2015-02-17&styles=&bbox=219786.0,4320640.0,252056.0,4350040.0&width=512&height=466&srs=EPSG:2100&format=application/openlayers
but the getfeatureinfo is not responding.

**Comment by nmalamos** [comment]
When clicking outside the study area the following appears. I probably can guess the reason why, but I can't think of the workaround needed to solve it:
![getfeatureinfo](https://cloud.githubusercontent.com/assets/11832693/7703037/5a0c5310-fe3d-11e4-9dfd-f71e04b18f3d.PNG)
