### ISSUE TITLE
Rename the "Home" button to "My Fields"

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#71]
Rename the "Home" button to "My Fields".
EL:
Αγροτεμάχια

Also place this: 
<b>Logged in as: <i>user_name</i></b>
in a cool spot

**Comment by kickapoo** [comment]
This issue is referring to the special templates files for `aira-irma` (repository https://github.com/openmeteo/aira-irma).
Issue is fixed by the commit: kickapoo@f588a5471f4f2f808701c9ff021174f6fe69fc32 in `openmeteo/aira-irma` commit tree. 

I am attaching two screenshots with the changes. When the user is logged in , `irma-aira` is getting  smaller with the appropriate message below the logo.

![screenshot 2015-04-23 12 47 45](https://cloud.githubusercontent.com/assets/5064612/7294658/05a4e114-e9b8-11e4-9848-a298732eb3a5.png)

![screenshot 2015-04-23 12 48 01](https://cloud.githubusercontent.com/assets/5064612/7294661/0b9a8d1c-e9b8-11e4-8364-fa4e2e63bfea.png)

**Comment by nmalamos** [comment]
The top left side of the page is overloaded.
Also, in Firefox the Language selection is aligned left. Only in Chrome it is aligned in the right side.
After that, my opinion is that the: <b>Logged in as: user_name</b> should be placed together with the <b>Logout</b> in the top right side.
Maybe we should consider a dropdown menu?

**Comment by kickapoo** [comment]
About the dropdown list is up to you to decide. Go to this http://getbootstrap.com/examples/theme/ , to check out an example dropdown.
<b>Logged in as: user_name</b>  was placed top left because is not active link. 

About the problem with Firefox, the form was `align="right"` attribute. The only solution is to create so divs with bootstrap grid system. If you need this feature please comment to do so.

**Comment by nmalamos** [comment]
Never mind the problem with Firefox, but we should mark it for the future (please do this).
Considering the dropdown menu there is only one available, so we use this as:
![screenshot 2015-04-24 13 55 19](https://cloud.githubusercontent.com/assets/11832693/7317482/f633a4b8-ea89-11e4-8f0d-10bb399c9bd3.png)

**Comment by kickapoo** [comment]
@nmalamos , there in no way to have default value on dropdown menu because the `first` click on the menu prompts the menu and can't be a active link. 
Also,  where `account` should redirect? You mean to the user-profile with the First,Last name Address?

**Comment by nmalamos** [comment]
Since, "My Fields" is the landing page after logging, do it like this:

Menu:
1)	My Fields 
2)	Description
3)	Account
4)     Logout (as separated link)

The user account (for now) can redirect to user-profile with the First,Last name Address.
Further information will be added in the future.

**Comment by nmalamos** [comment]
Add to account page the "Change password" function
EL:
Αλλαγή συνθηματικού

**Comment by kickapoo** [comment]
@nmalamos.
Previous translation of `Welcome` is `Καλωσήρθατε`.  Is it a problem? 
Also translation for `Menu` should be `Μενού`  or something else? 

![screenshot 2015-04-25 01 22 30](https://cloud.githubusercontent.com/assets/5064612/7329624/edcab162-eae9-11e4-982e-1cfc7660e687.png)

**Comment by nmalamos** [comment]
`Καλωσήρθατε` is fine.
Also, `Διαχείριση` (`Management`) is fine.

**Comment by kickapoo** [comment]
I closing this issue with the noting again that this issue is referring to the special templates files for `aira-irma` (repository https://github.com/openmeteo/aira-irma).
First commit `aira-irma`:  kickapoo@f588a54 in openmeteo/aira-irma commit tree.
Update `aira` to accept new menu: kickapoo@85e6af78072dcce244ddbdfabc0bad2bab2195ee
Second commit in `aira-irma`: kickapoo0cf1dc2d05d0b82e7bf992ebe3d3dec043d91f80

![screenshot 2015-04-25 11 08 11](https://cloud.githubusercontent.com/assets/5064612/7332182/806725d6-eb3b-11e4-8a33-9cb2f8279f7a.png)
![screenshot 2015-04-25 11 09 58](https://cloud.githubusercontent.com/assets/5064612/7332185/a5e022ea-eb3b-11e4-9190-3d3e6fc07cbd.png)

![screenshot 2015-04-25 11 10 48](https://cloud.githubusercontent.com/assets/5064612/7332187/c3969152-eb3b-11e4-9d90-bf58bbac944e.png)
