### ISSUE TITLE
System users and supervisors

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#78]
Following my email of 04/05/2015 13:07 and the skype conversation between myself, `aptiko` and Tsirogiannis, the Farmer (user) - Irrigation expert (supervisor) system should be implemented accordingly.

The only change to the mentioned specs is that when the Farmer (user) logs in, the system should not cancel  automatically the supervision of the account.

**Comment by nmalamos** [comment]
The supervisor should have the ability to access accounts that are supervised from the supervised account, forming a pyramid like system.

**Comment by kickapoo** [comment]
It is not clear to me, who determents if a `user` should be consider as `supervisor`. 
`users` can't be assumed that are potential `supervisors` for example in the issue #81 a list of supervisors should be created for normal 'users' to select. 

Maybe a special protected registration form should  lead to mail notification to `aira-irma` stuff  for reviewing `supervisors`

**Comment by nmalamos** [comment]
Considering this:
> It is not clear to me, who determents if a user should be consider as supervisor. 

This is my approach considering the main concept of our `user` roles system. 
Everyone should be able to act as a `supervisor` to an other account since the mentioned account renounces him as its `supervisor` (and he accepts).
Each account will be allowed to have only one **active** `supervisor` but if he chooses to select another, the only thing that he has to do is to delete the current `supervisor username` and enter a new one.
The `supervisors` must have the choice to accept or decline the invitations to supervise other accounts.

In this approach a potential `supervisors` list could exist, in order to provide some *ready to use* irrigation experts usernames and contact details that have been approved from IRMA project administration, as you propose. 
In my opinion, this could be easily implemented in an alternative way, by encouraging irrigation experts to make a post with their contact details and username at the relevant topic of the IRMA forum: http://www.irrigation-management.eu/forumx/irrigation-system-gr

I proposed the above roles system, having in mind a simple and **unattended** `user` role system, but since I have no knowledge of aira's database structure, I can't be sure that it can be implemented easily than the classic approach that you propose.
Also, I am not sure if this:
>The supervisor should have the ability to access accounts that are supervised from the supervised account, forming a pyramid like system.

is doable

@aptiko: As you can understand your opinion is crucial at this stage, since you were also present at Wednesday's meeting and you know aira's database structure.

**Comment by kickapoo** [comment]
The pyramid model, as far as I know, can be achieved through `recursion` model (Think it like a Parent(Superviror) has Childrens(Users) or in more practical example, a Blog has Categories that have sub Categories). 

As I wrote before, i think a more robust solution is the discrete separation of users and supervisor.

My flow structure is:
1. Link in the welcome page : "Do you want to be a supervisor?"
2. Redirect to a special form with fields like: name, pic, bio etc
3. Email notification to Mr.Malamos or Mr.Tsirogiannis: Do you accept the following as aira-supervisor?
    a) if no: mail back , you didn't accepted
   b) if yes: user can access the site sending him back the activation link (this is a tricky part )

Supervisor can:
1. Add fields with a indication of user name (a normal user may not want to use the system but only his supervisor, so supervisor should write all the necessary form of his user)
2. View/Update field that a aira-user has given access to him 


Also, a page will be added to aira, `our supervisors` with a list of name,pic, bio etc

**Comment by kickapoo** [comment]
@aptiko, a third party app for `recursive` model https://github.com/django-mptt/django-mptt . 
I have already used it and works just fine. 
The workflow wiil be: 
1. All users can register through the same mechanism
2. Somewhere, login  users can choose their `parent` user. 
3. If someone has set someone else as a parent, a new page with list of all Childs  will be there in order to access to child's fields.

**Comment by aptiko** [comment]
@kickapoo Anyone can be a supervisor. I enter the system and I say "I want kickapoo to be my supervisor". The system then tells you "aptiko wants you to be his supervisor", you accept, and then you have access to my fields. If I want you to be my supervisor, that's enough reason for you to be granted such access, there's no need to introduce additional bureaucracy. It is also not clear why we would need a pyramid, so [YAGNI](http://en.wikipedia.org/wiki/YAGNI).

Initially it seems we only need an extra field `supervisor` in the user profile, nullable, foreign key to `User`. However, it's a bit more complicated, because there is the procedure for assigning a supervisor. Let's have an additional field, `supervisor_accepted`, boolean, which is `False` at first, i.e. when the user has requested for the other person to be his supervisor, but the other hasn't accepted yet, and will become `True` upon acceptance. I'm not certain this will work in all cases, but let's start simple and then we grow it.

**Comment by aptiko** [comment]
Actually I think the above is too much complicated. How about no acceptance from the supervisor? I select `kickapoo` as my supervisor, that's it. The only thing that happens is that `kickapoo` has access to my fields. I don't have any motivation to do it illegitimately, and the only thing that will happen is that `kickapoo` will have that access, he won't be bothered otherwise.

So how about simply an extra field `supervisor` in the user profile, nullable, foreign key to `User`, and nothing else?

**Comment by kickapoo** [comment]
@aptiko, what ever you want, no problem with me. 
I will wait for @nmalamos  response  before i start the implementation.

**Comment by nmalamos** [comment]
I agree with @aptiko.
At this point we should implement a simple solution, since there is no feedback from the users' interaction to each other and to the system itself.
>select kickapoo as my supervisor, that's it. The only thing that happens is that kickapoo has access to my fields. I don't have any motivation to do it illegitimately, and the only thing that will happen is that kickapoo will have that access, he won't be bothered otherwise.
So how about simply an extra field supervisor in the user profile, nullable, foreign key to User, and nothing else?

@aptiko: Please provide further instructions to @kickapoo

**Comment by aptiko** [comment]
@kickapoo: Proceed with the implementation. I think it might be useful if you had this method:

    class Agrifield(models.Model):
        ...
        def can_edit(self, user):
            return (user == self.user) or (user == self.supervisor) or (user.is_superuser)

which you can then call like this:

    if afield.can_edit(request.user):
        # User can access the field

Having such a function is useful because in the future if we decide that my supervisor's supervisor is also my supervisor, than just by modifying that function things would work. Depending on how the code works, it may be more suitable to put such a function in the profile model as well as in the `Agrifield` model. Anyway, ask me for any difficulty.

**Comment by nmalamos** [comment]
Thinking it over, maybe a notification to the supervisor, that some `user` appointed him as a supervisor, it could be of use.
Maybe an e-mail with the relevant information (username, date etc.)
