### ISSUE TITLE
The popup message in the Openlayers map, should be translated in Greek

### ISSUE THREAD

**Issue by nmalamos** [openmeteo/aira#93]
The popup message in the Openlayers map, should be translated in Greek.

**Comment by nmalamos** [comment]
The term: PET which was the short version of Potential Evapotranspiration, may remain the same in Greek.

**Comment by aptiko** [comment]
This is non-trivial. We get the whole contents of the popup with WMS at this URL:

http://arta.irrigation-management.eu/mapserver-historical/?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&SRS=EPSG:3857&info_format=text/html&BBOX=2335941.5386874,4737781.6152649,2335991.5386874,4737831.6152649&WIDTH=2&HEIGHT=2&X=0&Y=0&LAYERS=Daily_temperature_2015-06-10,Daily_humidity_2015-06-10,Daily_wind_speed_2015-06-10,Daily_rain_2015-06-10,Daily_evaporation_2015-06-10,Daily_solar_radiation_2015-06-10&QUERY_LAYERS=Daily_temperature_2015-06-10,Daily_humidity_2015-06-10,Daily_wind_speed_2015-06-10,Daily_rain_2015-06-10,Daily_evaporation_2015-06-10,Daily_solar_radiation_2015-06-10

WMS does not support translation. There is no way (or it would be quite difficult) to request a specific language, because there is no parameter in the URL for specifying the language. I see, therefore, three solutions:

1. Provide the popup in only one language.
2. Use symbols instead of words; thermometer (u1F321) for temperature, droplet (u1F4A7) for humidity, blowing head (u1F32C) for wind, sun (u263c, ☼) for solar radiation, umbrella with rain (u2614, ☔) for rain, and the word PET. Unfortunately, with the exception of sun and rain, these are unusual characters, unsupported in most fonts. This solution would require adapting the Symbola font from http://users.teilar.gr/~g1951d/.
3. Change mapserver configuration so that it provides XML instead of HTML, and have the aira JavaScript parse that XML and create the HTML itself. This is even more work.

I wonder whether the existence of non-Greek users is such that would justify the cost of solutions (2) and (3).

**Comment by nmalamos** [comment]
Leave it as is, but have in mind that we might be asked to solve this one way or another.
I have some ideas but we will discuss them when time is right.
